local page = require("libs.TheKillerBunny.ActionWheelPlusPlus"):newPage("Coordinates", "minecraft:compass")
local x = page:newNumber("x", "minecraft:compass", function()
end, -30000000, 30000000, 1000, 0, 100000, 1)
local y = page:newNumber("y", "minecraft:compass", function()
end, -30000000, 30000000, 1000, 0, 100000, 1)
local z = page:newNumber("z", "minecraft:compass", function()
end, -30000000, 30000000, 1000, 0, 100000, 1)

page:newButton("Set to player pos", "minecraft:player_head", function()
   local pos = player:getPos():floor()
   x:setValue(pos.x)
   y:setValue(pos.y)
   z:setValue(pos.z)
end)
page:newButton("To overworld coordinates", "minecraft:grass_block", function()
   x:setValue(x:getValue() * 8)
   y:setValue(y:getValue() * 8)
   z:setValue(z:getValue() * 8)
end)
page:newButton("To nether coordinates", "minecraft:netherrack", function()
   x:setValue(math.floor(x:getValue() / 8))
   y:setValue(math.floor(y:getValue() / 8))
   z:setValue(math.floor(z:getValue() / 8))
end)

